config:
  # Configuration values to set up basic communication
  # Set your COM port e.g. COM3 for Windows, /dev/ttyACM0 for Linux...
  # Use AUTO for COM port auto-discovery (may not work on every setup)
  # COM_PORT: "/dev/ttyACM0"
  # COM_PORT: "COM3"
  COM_PORT: AUTO

  # Theme to use (located in res/themes)
  # Use the name of the folder as value
  THEME: Atlantis

  # Hardware sensors reading
  # Choose the appropriate method for reading your hardware sensors:
  # - PYTHON         use Python libraries (psutils, GPUtil...) to read hardware sensors (supports all OS but not all HW)
  # - LHM            use LibreHardwareMonitor library to read hardware sensors (Windows only - NEEDS ADMIN RIGHTS)
  # - STUB / STATIC  use random/static data instead of real hardware sensors
  # - AUTO           use the best method based on your OS: Windows OS will use LHM, other OS will use Python libraries
  HW_SENSORS: AUTO

  # Network interfaces
  # Linux/MacOS interfaces are named "eth0", "wlan0", "wlp1s0", "enp2s0"...
  # For Windows use the interfaces pretty name: "Ethernet 2", "Wi-Fi", ...
  # Leave the fields empty if the card does not exist on your setup
  ETH: Ethernet 4                 # Ethernet Card
  WLO: '' # Wi-Fi Card

  # for weather
  CITY: 
  # OpenWeatherMap API KEY. Can be obtained by creating a free account on https://home.openweathermap.org/users/sign_up
  API_KEY: 
  # Units used to display temperatures (metric - °C, imperial - °F, standard - °K)
  WEATHER_UNITS: metric

display:
  # Display revision: A for Turing 3.5" and UsbPCMonitor 3.5"/5", B for Xuanfang 3.5" (inc. flagship), C for Turing 5"
  # Use SIMU for 3.5" simulated LCD (image written in screencap.png) or SIMU5 for 5" simulated LCD
  # To identify your revision: https://github.com/mathoudebine/turing-smart-screen-python/wiki/Hardware-revisions
  REVISION: A

  # Display Brightness
  # Set this as the desired %, 0 being completely dark and 100 being max brightness
  # Warning: revision A display can get hot at high brightness!
  BRIGHTNESS: 8

  # Display reverse: true/false
  # Set to true to reverse display orientation (landscape <-> reverse landscape, portrait <-> reverse portrait)
  # Note: Display basic orientation (portrait or landscape) is defined by the theme you have selected
  DISPLAY_REVERSE: false

  # on Sleep, some devices turn off USB power so the display will lose the background and static texts
  # on Wake from Sleep only dynamic texts are redrawn.
  # This option allows a refresh (redraw) of background and static texts on wake from sleep
  REDRAW_BACKGROUND: true
